import React, { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

import "bootstrap/dist/css/bootstrap.min.css";
import { Button } from "react-bootstrap";
import { NextApiResponse } from "next";

export default function Home() {
  const [data, setData] = useState({});
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [check, setCheck] = useState(false);

  const handleSubmit = async (e: any) => {
    e.preventDefault();

    setCheck(true);

    let data = {
      name: e.target.name.value,
      email: e.target.email.value,
      message: e.target.message.value,
    };

    setData(data);

    setName(e.target.name.value);
    setEmail(e.target.email.value);
    setMessage(e.target.message.value);
  };

  const handleReset = () => {
    setIsSubmitted(false);
    setCheck(false);
  };

  const handleDone = async () => {
    await fetch("api/contact", {
      method: "POST",
      headers: {
        Accept: "application/json, text/plain",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    }).then((res) => {
      if (res.status === 200) {
        setCheck(false);
        setIsSubmitted(true);
      }
    });
  };

  if (check) {
    return (
      <>
        <Head>
          <title>内容を確認 - Contact App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="container mt-5">
          <h2 className="md-3">内容を確認</h2>
          <div className="mb-3">
            <label htmlFor="name" className="form-label">
              お名前
            </label>
            <input
              type="text"
              id="name"
              className="form-control"
              value={name}
              aria-label="readonly"
              readOnly
            />
          </div>
          <div className="mb-3">
            <label htmlFor="email" className="form-label">
              メールアドレス
            </label>
            <input
              type="text"
              id="email"
              className="form-control"
              value={email}
              aria-label="readonly"
              readOnly
            />
          </div>
          <div className="mb-3">
            <label htmlFor="message" className="form-label">
              お問い合わせ内容
            </label>
            <textarea
              id="message"
              className="form-control"
              value={message}
              aria-label="readonly"
              style={{height: "200px"}}
              readOnly
            ></textarea>
          </div>
          <Button variant="danger" onClick={handleDone}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              className="bi bi-envelope"
              viewBox="0 0 16 16"
            >
              <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
            </svg>
            <span className="ms-2">送信</span>
          </Button>
        </div>
      </>
    );
  }

  if (isSubmitted) {
    return (
      <>
        <Head>
          <title>Contact App - Aroma</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="container mt-5">
          <h2 className="md-3">Confirmation</h2>
          <div className="alert alert-success" role="alert">
            お問い合わせを受け付けました。ありがとうございます！
          </div>
          <Button variant="primary" onClick={handleReset}>
            別のお問い合わせをする
          </Button>
        </div>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Contact App - Aroma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-5">
        <h2 className="md-3">Next.js Gmail App</h2>
        <form onSubmit={handleSubmit}>
          <div className="mb-3 form-floating">
            <input
              type="text"
              id="name"
              required
              className="form-control"
              placeholder="山田　太郎"
            />
            <label htmlFor="name">お名前</label>
          </div>
          <div className="mb-3 form-floating">
            <input
              type="email"
              id="email"
              required
              className="form-control"
              placeholder="mail@example.com"
            />
            <label htmlFor="email">メールアドレス</label>
          </div>
          <div className="mb-3 form-floating">
            <textarea
              name="message"
              id="message"
              className="form-control"
              required
              placeholder="テキスト"
              style={{height: "200px"}}
            ></textarea>
            <label htmlFor="message">
              お問い合わせ内容
            </label>
          </div>
          <button className="btn btn-primary" type="submit">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              className="bi bi-envelope"
              viewBox="0 0 16 16"
            >
              <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
            </svg>
            <span className="ps-2">確認画面へ</span>
          </button>
        </form>
      </div>
    </>
  );
}
